FROM node:23

WORKDIR /app

# Les dépendances seront installées via le volume monté
# Pas besoin de copier les fichiers car ils seront montés via le volume

# Exposer le port
EXPOSE 8081

# Démarrer l'application en mode développement
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]