services:
   web:
      image: php:8.2-apache
      build: .
      container_name: app_sf_web
      env_file:
         -  .env
      networks:
         - rezo_app_sf_web
      ports:
         - "8050:8000"
      volumes:
         - ../backend:/var/www/html
   db:
      image: postgres:14
      container_name: app_sf_db
      ports:
         - "5432:5432"
      networks:
         - rezo_app_sf_web
         - rezo_app_sf_pgadmin
      volumes:
         - postgres_data:/var/lib/postgresql/data
      environment:
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}

   pgadmin:
      image: dpage/pgadmin4
      container_name: app_sf_pgadmin
      networks:
         - rezo_app_sf_pgadmin
      ports:
         - "8060:80"
      environment:
         - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
         - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
         - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIG_SERVER_MODE}

   frontend:
      build:
         context: ..
         dockerfile: docker-config/Dockerfile_vue
      container_name: app_vue_frontend
      networks:
         - rezo_app_sf_web
      ports:
         - "8080:8080"
      volumes:
         - ../frontend:/app
      environment:
         - NODE_ENV=development
      command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

   panel-admin:
      build:
         context: ..
         dockerfile: docker-config/Dockerfile_vue_panelAdmin
      container_name: panel_admin
      networks:
         - rezo_app_sf_web
      ports:
         - "8081:8081"
      volumes:
         - ../panelAdmin:/app
      environment:
         - NODE_ENV=development
      command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

networks:
   rezo_app_sf_web:
   rezo_app_sf_pgadmin:

volumes:
   sf:
   postgres_data: